version: '2'

services:
  frontend:
    image: fulltimeforce/frontend
    build: ./frontend/app/
    ports: 
      - 8080:8080
    depends_on: 
      - backend
    env_file:
      - ./frontend/app/.env

  backend:
    image: fulltimeforce/backend
    build: ./backend
    ports: 
      - 3000:3000
    env_file:
      - ./backend/.env
